SmsDelivery/ViewModels/CampaignViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using SmsDelivery.Model;

namespace SmsDelivery.ViewModels
{
    public class CampaignViewModel
    {
        public CampaignViewModel()
        {
            SubscriberGroupViews = new List<SubscriberGroupViewModel>();
        }
        public string Name { get; set; }
        public int? TemplateId { get; set; }
        public string Sender { get; set; }
        public string Body { get; set; }
        public bool CreateSenderName { get; set; }
        public int SaveSenderNameId { get; set; }
        public bool ScheduleDate { get; set; }
        public DateTime? ScheduledDate { get; set; }
        public List<SubscriberGroupViewModel> SubscriberGroupViews { get; set; }
    }
}

SmsDelivery/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SmsDelivery.Model;
using SmsDelivery.Model.Enums;
using SmsDelivery.Model.Interfaces;
using SmsDelivery.Models.FilteringAndSorting;
using SmsDelivery.ViewModels;

namespace SmsDelivery.Controllers
{
    public class CampaignsController : Controller
    {
        public string UserId => User.Identity.GetUserId();
        public ICampaignRepository CampaignRepository { get; set; }
        public ICampaignSubscribersGroupsRepository CampaignSubscribersGroupsRepository { get; set; }
        public ITemplatesRepository TemplatesRepository { get; set; }
        public ISubscriberGroupRepository SubscriberGroupRepository { get; set; }
        public ISavedSenderNameRepository SavedSenderNameRepository { get; set; }

        public CampaignsController(ICampaignRepository campaignRepository, ITemplatesRepository templatesRepository, 
            ISubscriberGroupRepository subscriberGroupRepository, ISavedSenderNameRepository savedSenderNameRepository,
            ICampaignSubscribersGroupsRepository campaignSubscribersGroupsRepository)
        {
            CampaignRepository = campaignRepository;
            TemplatesRepository = templatesRepository;
            SubscriberGroupRepository = subscriberGroupRepository;
            SavedSenderNameRepository = savedSenderNameRepository;
            CampaignSubscribersGroupsRepository = campaignSubscribersGroupsRepository;
        }
        // GET: Campaigns
        public ActionResult Index(CampaignsFilteredModel campaignsFilteredModel, int? page)
        {
            var pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;
            if (campaignsFilteredModel == null)
            {
                campaignsFilteredModel = new CampaignsFilteredModel();
            }
            if (campaignsFilteredModel.PageSize <= 0)
            {
                campaignsFilteredModel.PageSize = 10;
            }

            var campaings = CampaignRepository.GetAll();

            campaignsFilteredModel.ProcessData(campaings, "ID", true, pageNumber);
            return View(campaignsFilteredModel);
        }

        public ActionResult Create()
        {
            var model = new CampaignViewModel();
            var subscriberGroup = new SubscriberGroupViewModel();
            subscriberGroup.SubscriberGroups = new SelectList(SubscriberGroupRepository.GetAll().Where(x => x.CustomerId.Equals(UserId)).ToList(), "Id", "Name");
            model.SubscriberGroupViews.Add(subscriberGroup);

            ViewBag.Templates = new SelectList(TemplatesRepository.GetAll().Where(x => x.CustomerId.Equals(UserId)).ToList(), "Id", "Name");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CampaignViewModel model)
        {
            if (ModelState.IsValid)
            {
                var campaign = new Campaing();
                campaign.Name = model.Name;
                campaign.CampaignTypeId = (int) CampaignTypes.Sms;
                campaign.CreatedDate = DateTime.Now;
                if (model.ScheduleDate)
                {
                    campaign.Status = (int) CampaignStatus.Scheduled;
                    campaign.ScheduledDate = model.ScheduledDate;
                }
                else
                {
                    campaign.Status = (int) CampaignStatus.New;
                }

                if (model.TemplateId.HasValue)
                {
                    campaign.TemplateId = model.TemplateId.Value;
                }

                campaign.Body = model.Body;
                campaign.Cost = 0;
                campaign.CustomerId = UserId;

                CampaignRepository.Insert(campaign);
                CampaignRepository.Save();

                foreach (var subscriberGroup in model.SubscriberGroupViews)
                {
                    var group = new CampaingSubscriberGroup();
                    group.CampaignId = campaign.Id;
                    group.GroupId = subscriberGroup.SubscriberGroupId;
                    CampaignSubscribersGroupsRepository.Insert(group);
                }
                CampaignSubscribersGroupsRepository.Save();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult SubscriberGroupEntryRow()
        {
            var subscriberGroup = new SubscriberGroupViewModel();
            subscriberGroup.SubscriberGroups = new SelectList(SubscriberGroupRepository.GetAll().Where(x => x.CustomerId.Equals(UserId)).ToList(), "Id", "Name");
            return PartialView("_SubscriberGroupEntry", subscriberGroup);
        }

        public JsonResult SenderNamesSearch(string query)
        {
            var names = SavedSenderNameRepository.GetAll()
                .Where(x => x.CustomerId.Equals(UserId) && x.Name.Contains(query)).Select(x => new {x.Id, x.Name}).ToList();

            return Json(names, JsonRequestBehavior.AllowGet);
        }
    }
}

SmsDelivery/Controllers/SubscribersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using SmsDelivery.Filters;
using SmsDelivery.Model;
using SmsDelivery.Model.Interfaces;
using SmsDelivery.Models;
using SmsDelivery.Models.FilteringAndSorting;

namespace SmsDelivery.Controllers
{
    [Authorize]
    public class SubscribersController : Controller
    {
        public ISubscriberRepository SubscriberRepository { get; set; }
        public ICountryRepository CountryRepository { get; set; }
        public ISubscriberGroupRepository SubscriberGroupRepository { get; set; }

        public SubscribersController(ISubscriberRepository subscriberRepository, ICountryRepository countryRepository, ISubscriberGroupRepository subscriberGroupRepository)
        {
            SubscriberRepository = subscriberRepository;
            CountryRepository = countryRepository;
            SubscriberGroupRepository = subscriberGroupRepository;
        }

        // GET: Subscribers
        public ActionResult Index(SubscribersFilteredModel filteredModel, int? page)
        {
            var pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;

            if (filteredModel == null)
            {
                filteredModel = new SubscribersFilteredModel();
            }
            if (filteredModel.PageSize <= 0)
            {
                filteredModel.PageSize = 10;
            }

            var subscribers = SubscriberRepository.GetAll();

            filteredModel.ProcessData(subscribers, "ID", true, pageNumber);
            return View(filteredModel);
        }

        // GET: Subscribers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = SubscriberRepository.GetById(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // GET: Subscribers/Create
        public ActionResult GetCreatePartial()
        {
            ViewBag.CountryId = new SelectList(CountryRepository.GetAll().ToList(), "Id", "Name");
            ViewBag.SubscriberGroupId = new SelectList(SubscriberGroupRepository.GetAll().ToList(), "Id", "Name");
            return PartialView("_CreateModal");
        }

        // POST: Subscribers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "Id,Name,Surname,Phone,Email,Address,City,CountryId,SubscriberGroupId")] Subscriber subscriber)
        {
            if (ModelState.IsValid)
            {
                subscriber.CreatedDate = DateTime.Now;
                SubscriberRepository.Insert(subscriber);
                SubscriberRepository.Save();
                return Json(new Response{ Success = true, Message = subscriber.Id.ToString()}, JsonRequestBehavior.AllowGet);
            }
            ViewBag.CountryId = new SelectList(CountryRepository.GetAll().ToList(), "Id", "Name");
            ViewBag.SubscriberGroupId = new SelectList(SubscriberGroupRepository.GetAll().ToList(), "Id", "Name");
            return Json(new Response {Success = false, Errors = ModelState.Keys.ToList()});
        }

        // GET: Subscribers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = SubscriberRepository.GetById(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryId = new SelectList(CountryRepository.GetAll().ToList(), "Id", "Name");
            ViewBag.SubscriberGroupId = new SelectList(SubscriberGroupRepository.GetAll().ToList(), "Id", "Name");
            return View(subscriber);
        }

        // POST: Subscribers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,Phone,Email,Address,City,CountryId,CreatedDate")] Subscriber subscriber)
        {
            if (ModelState.IsValid)
            {
                SubscriberRepository.Update(subscriber);
                SubscriberRepository.Save();
                return RedirectToAction("Index");
            }
            ViewBag.CountryId = new SelectList(CountryRepository.GetAll().ToList(), "Id", "Name");
            ViewBag.SubscriberGroupId = new SelectList(SubscriberGroupRepository.GetAll().ToList(), "Id", "Name");
            return View(subscriber);
        }

        // GET: Subscribers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = SubscriberRepository.GetById(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // POST: Subscribers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SubscriberRepository.Delete(id);
            SubscriberRepository.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult DeleteSelected(int[] ids)
        {
            if (ids.Length > 0)
            {
                foreach (var id in ids)
                {
                    SubscriberRepository.Delete(id);
                }
                SubscriberRepository.Save();

                return Json(new Response() {Success = true});
            }
            return Json(new Response() {Success = false});
        }
    }
}

SmsDelivery/Views/Campaigns/Create.cshtml
@using PagedList.Mvc
@using SmsDelivery.Helpers
@using SmsDelivery.Models
@using SmsDelivery.ViewModels
@model SmsDelivery.ViewModels.CampaignViewModel

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Create a new campaign</h4>
            <hr/>
        </div>
        <div class="content table-responsive table-full-width mt-2">
            @using (Html.BeginForm("Create", "Campaigns", FormMethod.Post, new { role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Campaign name")
                            @Html.TextBoxFor(model => model.Name, new {@class = "form-control"})
                            @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Templates")
                            @Html.DropDownListFor(model => model.TemplateId, (IEnumerable<SelectListItem>) ViewBag.Templates, "Choose template", new {@class = "form-control"})
                            @Html.ValidationMessageFor(model => model.TemplateId, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-6">
                        @Html.Label("Recipients", new { @class = "col-lg-4 control-label" })
                        <div id="subscriberGroups">
                            @foreach (SubscriberGroupViewModel group in Model.SubscriberGroupViews)
                            {
                                Html.RenderPartial("_SubscriberGroupEntry", group);
                            }
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2">
                                <a class="btn btn-primary" id="addAnother" href="#">Добавить группу</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @Html.HiddenFor(model => model.SaveSenderNameId)
                        <div class="form-group">
                            @Html.Label("Sender")
                            @*@Html.TextBoxFor(model => model.Sender, new { @class = "form-control", data_autocomplete_source = Url.Action("SenderNamesSearch", "Campaigns") })*@
                            @Html.AutocompleteFor(model => model.Sender, model => model.SaveSenderNameId, "SenderNamesSearch", "Campaigns", false)
                        </div>
                    </div>
                    <div class="col-md-4 mt-25px">
                        <span>Save sender name</span>
                        @Html.CheckBoxFor(model => model.CreateSenderName, new {@class = "switch-plain"})
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            @Html.Label("Message")
                            @Html.TextAreaFor(model => model.Body, new {@class = "form-control", @rows = "6" })
                            @Html.ValidationMessageFor(model => model.Body, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 mt-25px">
                        <span>Schedule campaign</span>
                        @Html.CheckBoxFor(model => model.ScheduleDate, new { @class = "switch-plain" })
                    </div>
                    <div class="col-md-6 mt-20px">
                        <div class='form-group'>
                            @Html.TextBoxFor(model => model.ScheduledDate, new { @class = "form-control datetimepicker", placeholder = "Choose date and time" })
                            @Html.ValidationMessageFor(model => model.ScheduledDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="text-center col-md-10">
                    <button type="submit" class="btn btn-default">Create campaign</button>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/Scripts/campaign-create.js")
    @Scripts.Render("~/Scripts/datetimepicker-init.js")
    @Scripts.Render("~/Scripts/autocomplete-init.js")
}

SmsDelivery/Views/Campaigns/Index.cshtml
@using PagedList.Mvc
@model SmsDelivery.Models.FilteringAndSorting.CampaignsFilteredModel

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Campaigns</h4>
            <div class="pt-15px">
                <div class="col-md-3">
                    <a href="@Url.Action("Create")" class="text-uppercase small"><i class="ti-plus"></i><b style="padding-left: 10px">New Campaign</b></a>
                </div>
                @*<div class="col-md-3">
                    <a href="#" class="text-uppercase small"><i class="ti-angle-down"></i><b style="padding-left: 10px">Filter By Group</b></a>
                </div>*@
            </div>
            @*<div style="padding-top: 15px">
                
            </div>*@
        </div>
        <div class="content table-responsive table-full-width mt-2">
            <div class="pt-15px">
                @*<div class="col-md-4">
                    @using (Html.BeginForm("Index", "Subscribers", FormMethod.Post, new {id = "subscriberSearchForm"}))
                    {
                        @Html.HiddenFor(model => model.PageSize)
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.SearchText, new {@class = "form-control", placeholder = "Search by name..."})
                            <button type="submit" class="input-group-addon"><i class="fa fa-search"></i></button>
                        </div>
                    }
                </div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Move To Group</button>
                </div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase delete-checked-subscribers" data-url="@Url.Action("DeleteSelected")" style="font-size: 12px">Delete</button>
                </div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Send Sms</button>
                </div>*@
            </div>
            <div class="pt-55px">
                <table class="table table-hover">
                    <thead>
                    <th>Date</th>
                    <th>Campaign Name</th>
                    <th>Status</th>
                    </thead>
                    <tbody>
                    @if (Model.Campaings.Count > 0)
                    {
                        foreach (var item in Model.Campaings)
                        {
                            <tr>
                                <td></td>
                                <td>@item.CreatedDate</td>
                                <td>@item.Name</td>
                                <td>@item.Status</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="text-center" id="noDataRow">No data</td>
                        </tr>
                    }

                    </tbody>
                </table>
            </div>
            <div class="pt-15px">
                @*<div class="col-md-3">Выбрано 3 записи</div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Move To Group</button>
                </div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase delete-checked-subscribers" data-url="@Url.Action("DeleteSelected")" style="font-size: 12px">Delete</button>
                </div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Send Sms</button>
                </div>*@
            </div>
            
        </div>
    </div>
    <div class="pt-15px">
        <div class="pull-right col-md-3">
            @Html.PagedListPager(Model.Campaings, page => Url.Action("Index", new {page, Model.PageSize}))
        </div>
    </div>
</div>

SmsDelivery/Views/Campaigns/_SubscriberGroupEntry.cshtml
@using SmsDelivery.Helpers
@model SmsDelivery.ViewModels.SubscriberGroupViewModel

@using (Html.BeginCollectionItem("SubscriberGroupViews"))
{
    
    <div class="form-group">
        <div class="col-lg-10">
            @Html.DropDownListFor(model => model.SubscriberGroupId, Model.SubscriberGroups, "Choose group", new { @class = "form-control", style="float: left; width: 95%;" })
            @Html.ValidationMessageFor(model => model.SubscriberGroupId)
            <label class="pull-right">
                <a href="#" onclick="$(this).parent().parent().parent().remove();">x</a>
            </label>
        </div>
    </div>
    
}