SmsDelivery/ViewModels/SubscriberGroupViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using SmsDelivery.Model;

namespace SmsDelivery.ViewModels
{
    public class SubscriberGroupViewModel
    {
        public int SubscriberGroupId { get; set; }
        public SelectList SubscriberGroups { get; set; }
    }
}

SmsDelivery/Controllers/SubscriberGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SmsDelivery.Model;
using SmsDelivery.Model.Interfaces;
using SmsDelivery.Models;
using SmsDelivery.Models.FilteringAndSorting;

namespace SmsDelivery.Controllers
{
    [Authorize]
    public class SubscriberGroupsController : Controller
    {
        //private SmsDeliveryDbEntities db = new SmsDeliveryDbEntities();
        public ISubscriberGroupRepository SubscriberGroupRepository { get; set; }

        public SubscriberGroupsController(ISubscriberGroupRepository subscriberGroupRepository)
        {
            SubscriberGroupRepository = subscriberGroupRepository;
        }

        // GET: SubscriberGroups
        public ActionResult Index(SubscriberGroupsFilteredModel filteredModel, int? page)
        {
            var pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;

            if (filteredModel == null)
            {
                filteredModel = new SubscriberGroupsFilteredModel();
            }
            if (filteredModel.PageSize <= 0)
            {
                filteredModel.PageSize = 10;
            }

            var subscribers = SubscriberGroupRepository.GetAll();
            filteredModel.ProcessData(subscribers, "ID", true, pageNumber);

            return View(filteredModel);
        }

        // GET: SubscriberGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubscriberGroup subscriberGroup = SubscriberGroupRepository.GetById(id);
            if (subscriberGroup == null)
            {
                return HttpNotFound();
            }
            return View(subscriberGroup);
        }

        // GET: SubscriberGroups/Create
        public ActionResult CreateModal()
        {
            return PartialView("_CreateModal");
        }

        // POST: SubscriberGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "Id,Name,Description,CustomerId,IsMain")] SubscriberGroup subscriberGroup)
        {
            if (ModelState.IsValid)
            {
                subscriberGroup.CustomerId = User.Identity.GetUserId();
                SubscriberGroupRepository.Insert(subscriberGroup);
                SubscriberGroupRepository.Save();
                return Json(new Response { Success = true, Message = subscriberGroup.Id.ToString()});
            }

            return Json(new Response { Success = false });
        }

        // GET: SubscriberGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubscriberGroup subscriberGroup = SubscriberGroupRepository.GetById(id);
            if (subscriberGroup == null)
            {
                return HttpNotFound();
            }
            return View(subscriberGroup);
        }

        // POST: SubscriberGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CustomerId,IsMain")] SubscriberGroup subscriberGroup)
        {
            if (ModelState.IsValid)
            {
                SubscriberGroupRepository.Update(subscriberGroup);
                SubscriberGroupRepository.Save();
                return RedirectToAction("Index");
            }
            return View(subscriberGroup);
        }

        // GET: SubscriberGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubscriberGroup subscriberGroup = SubscriberGroupRepository.GetById(id);
            if (subscriberGroup == null)
            {
                return HttpNotFound();
            }
            return View(subscriberGroup);
        }

        // POST: SubscriberGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SubscriberGroup subscriberGroup = SubscriberGroupRepository.GetById(id);
            SubscriberGroupRepository.Delete(subscriberGroup);
            SubscriberGroupRepository.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult DeleteSelected(int[] ids)
        {
            if (ids.Length > 0)
            {
                foreach (var id in ids)
                {
                    SubscriberGroupRepository.Delete(id);
                }
                SubscriberGroupRepository.Save();

                return Json(new Response() { Success = true });
            }
            return Json(new Response() { Success = false });
        }
    }
}

SmsDelivery/Views/SubscriberGroups/Create.cshtml
@model SmsDelivery.Model.SubscriberGroup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubscriberGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMain)
                    @Html.ValidationMessageFor(model => model.IsMain, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SmsDelivery/Views/SubscriberGroups/Delete.cshtml
@model SmsDelivery.Model.SubscriberGroup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubscriberGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SmsDelivery/Views/SubscriberGroups/Details.cshtml
@model SmsDelivery.Model.SubscriberGroup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SubscriberGroup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SmsDelivery/Views/SubscriberGroups/Edit.cshtml
@model SmsDelivery.Model.SubscriberGroup

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubscriberGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMain)
                    @Html.ValidationMessageFor(model => model.IsMain, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SmsDelivery/Views/SubscriberGroups/Index.cshtml
@using PagedList.Mvc
@model SmsDelivery.Models.FilteringAndSorting.SubscriberGroupsFilteredModel

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Subscribers</h4>
            <div class="pt-15px">
                <div class="col-md-3">
                    <a href="#" data-toggle="modal" data-target="#subscriberGroupCreateModal" class="text-uppercase small"><i class="ti-plus"></i><b style="padding-left: 10px">New Group</b></a>
                </div>
            </div>
        </div>
        <div class="content table-responsive table-full-width">
            <div class="pt-15px">
                <div class="col-md-4">
                    @using (Html.BeginForm("Index", "SubscriberGroups", FormMethod.Post, new { id = "subscriberGroupSearchForm" }))
                    {
                        @Html.HiddenFor(model => model.PageSize)
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.SearchText, new { @class = "form-control", placeholder = "Search by name..." })
                            <button type="submit" class="input-group-addon"><i class="fa fa-search"></i></button>
                        </div>
                    }
                </div>
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Merge Groups</button>
                </div>*@
                <div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase delete-checked-groups" data-url="@Url.Action("DeleteSelected")" style="font-size: 12px">Delete</button>
                </div>
                @*<div class="col-md-3 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Start Campaing</button>
                </div>*@
            </div>
            <div class="pt-55px">
                <table class="table table-hover">
                    <thead>
                    <th></th>
                    <th>Group Name</th>
                    <th>Contacts</th>
                    <th>Note</th>
                    </thead>
                    <tbody>
                        @if (Model.SubscriberGroups.Count > 0)
                        {
                            foreach (var item in Model.SubscriberGroups)
                            {
                                <tr>
                                    <td><input data-id="@item.Id" id="ToDelete" name="ToDelete" type="checkbox" value="true"></td>
                                    <td>@item.Name</td>
                                    <td>@item.Subscribers.Count</td>
                                    <td>@item.Description</td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="4" class="text-center" id="noDataRow">No data</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="pt-15px">
                @*<div class="col-md-3">Выбрано 3 записи</div>*@
                @*<div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Merge Groups</button>
                </div>*@
                <div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase delete-checked-groups" data-url="@Url.Action("DeleteSelected")" style="font-size: 12px">Delete</button>
                </div>
                @*<div class="col-md-3 pull-right">
                    <button class="btn btn-default text-uppercase" style="font-size: 12px">Start Campaing</button>
                </div>*@
            </div>

        </div>
    </div>
    <div class="pt-15px">
        <div class="pull-right col-md-3">
            @Html.PagedListPager(Model.SubscriberGroups, page => Url.Action("Index", new { page, Model.SearchText, Model.PageSize }))
        </div>
    </div>
</div>
@section modal{
    @Html.Action("CreateModal")
}
@section scripts
{
    @Scripts.Render("/Scripts/subscriber-group.js")
}

SmsDelivery/Views/SubscriberGroups/_CreateModal.cshtml
@model SmsDelivery.Model.SubscriberGroup
<div class="modal fade" id="subscriberGroupCreateModal" role="dialog">
    <div class="modal-dialog">
    
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #d3d3d3;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Group</h4>
            </div>
            <div class="modal-body" style="background-color: #d3d3d3;">
            @using (Html.BeginForm("Create", "SubscriberGroups", FormMethod.Post, new { id = "subscriberGroupCreateModalForm", data_url = Url.Action("Create") })) 
            {
                @Html.AntiForgeryToken()
    
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="alert alert-danger hide" id="validationErrors">
                        <ul></ul>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
            </div>
        </div>
      
    </div>
</div>