SmsDelivery/Controllers/TemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SmsDelivery.Model;
using SmsDelivery.Model.Interfaces;
using SmsDelivery.Models;
using SmsDelivery.Models.FilteringAndSorting;

namespace SmsDelivery.Controllers
{
    public class TemplatesController : Controller
    {
        public string UserId => User.Identity.GetUserId();
        public ITemplatesRepository TemplatesRepository { get; set; }
        public ITemplateTypesRepository TemplateTypesRepository { get; set; }

        public TemplatesController(ITemplatesRepository templatesRepository, ITemplateTypesRepository templateTypesRepository)
        {
            TemplatesRepository = templatesRepository;
            TemplateTypesRepository = templateTypesRepository;
        }

        // GET: Templates
        public ActionResult Index(TemplatesFilteredModel templatesFilteredModel, int? page)
        {
            var pageNumber = Request.HttpMethod == "GET" ? page ?? 1 : 1;

            if (templatesFilteredModel == null)
            {
                templatesFilteredModel = new TemplatesFilteredModel();
            }

            if (templatesFilteredModel.PageSize <= 0)
            {
                templatesFilteredModel.PageSize = 10;
            }

            var templates = TemplatesRepository.GetAll();

            templatesFilteredModel.ProcessData(templates, "id", true, pageNumber);

            return View(templatesFilteredModel);
        }

        public ActionResult CreateModal()
        {
            ViewBag.TemplateTypes = new SelectList(TemplateTypesRepository.GetAll().ToList(), "Id", "Type");
            return PartialView("_CreateModal");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(Template template)
        {
            if (ModelState.IsValid)
            {
                template.CustomerId = UserId;
                TemplatesRepository.Insert(template);
                TemplatesRepository.Save();

                return Json(new Response {Success = true, Body = template});
            }

            return Json(new Response() {Success = false});
        }

        public ActionResult EditModal()
        {
            ViewBag.TemplateTypes = new SelectList(TemplateTypesRepository.GetAll().ToList(), "Id", "Type");
            return PartialView("_EditModal");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(Template template)
        {
            if (ModelState.IsValid)
            {
                TemplatesRepository.Update(template);
                TemplatesRepository.Save();

                return Json(new Response() {Success = true});
            }
            return Json(new Response() {Success = false});
        }

        [HttpPost]
        public JsonResult DeleteSelected(int[] ids)
        {
            if (ids.Length > 0)
            {
                foreach (var id in ids)
                {
                    TemplatesRepository.Delete(id);
                }
                TemplatesRepository.Save();

                return Json(new Response() { Success = true });
            }
            return Json(new Response() { Success = false });
        }
    }
}

SmsDelivery/Views/Templates/Index.cshtml
@using PagedList.Mvc
@model SmsDelivery.Models.FilteringAndSorting.TemplatesFilteredModel

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12">
    <div class="card card-plain">
        <div class="header">
            <h4 class="title">Templates</h4>
            <div class="pt-15px">
                <div class="col-md-3">
                    <a href="#" data-toggle="modal" data-target="#templateCreateModal" class="text-uppercase small"><i class="ti-plus"></i><b style="padding-left: 10px">New Template</b></a>
                </div>
                @*<div class="col-md-3">
                    <a href="#" class="text-uppercase small"><i class="ti-angle-down"></i><b style="padding-left: 10px">Filter By Group</b></a>
                </div>*@
            </div>
            @*<div style="padding-top: 15px">
                
            </div>*@
        </div>
        <div class="content table-responsive table-full-width mt-2">
            <div class="pt-55px">
                <table class="table table-hover">
                    <thead>
                    <th></th>
                    @*<th>Phone</th>
                    <th>Contact Name</th>*@
                    <th>Name</th>
                    <th>Type</th>
                    </thead>
                    <tbody>
                    @if (Model.Templates.Count > 0)
                    {
                        foreach (var item in Model.Templates)
                        {
                            <tr>
                                <td><input data-id="@item.Id" id="ToDelete" name="ToDelete" type="checkbox" value="true"></td>
                                <td><a href="#" data-toggle="modal" data-target="#templateEditModal">@item.Name</a></td>
                                <td>@item.TemplateType.Type</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="text-center" id="noDataRow">No data</td>
                        </tr>
                    }

                    </tbody>
                </table>
            </div>
            <div class="pt-15px">
                @*<div class="col-md-3">Выбрано 3 записи</div>*@
                @*<div class="col-md-2 pull-right">
            <button class="btn btn-default text-uppercase" style="font-size: 12px">Move To Group</button>
        </div>*@
                <div class="col-md-2 pull-right">
                    <button class="btn btn-default text-uppercase delete-checked-templates" data-url="@Url.Action("DeleteSelected")" style="font-size: 12px">Delete</button>
                </div>
                @*<div class="col-md-2 pull-right">
            <button class="btn btn-default text-uppercase" style="font-size: 12px">Send Sms</button>
        </div>*@
            </div>
        </div>
    </div>
    <div class="pt-15px">
        <div class="pull-right col-md-3">
            @Html.PagedListPager(Model.Templates, page => Url.Action("Index", new {page, Model.PageSize}))
        </div>
    </div>
</div>
@section modal{
    @Html.Action("CreateModal")
    @Html.Action("EditModal")
}
@section scripts
{
    @Scripts.Render("/Scripts/template.js")
}

SmsDelivery/Views/Templates/_CreateModal.cshtml
@model SmsDelivery.Model.Template
<div class="modal fade" id="templateCreateModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #d3d3d3;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create new template</h4>
            </div>
            <div class="modal-body" style="background-color: #d3d3d3;">
                @using (Html.BeginForm("Create", "Templates", FormMethod.Post, new { id = "templateCreateModalForm", data_url = Url.Action("Create") }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="alert alert-danger hide" id="validationErrors">
                            <ul></ul>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } }))
                                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TemplateTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.TemplateTypeId, (IEnumerable<SelectListItem>) ViewBag.TemplateTypes,  new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TemplateTypeId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>

SmsDelivery/Views/Templates/_EditModal.cshtml
@model SmsDelivery.Model.Template

<div class="modal fade" id="templateEditModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #d3d3d3;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit template</h4>
            </div>
            <div class="modal-body" style="background-color: #d3d3d3;">
                @using (Html.BeginForm("Edit", "Templates", FormMethod.Post, new { id = "templateEditModalForm", data_url = Url.Action("Edit") }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="alert alert-danger hide" id="validationErrors">
                            <ul></ul>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.TemplateTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.TemplateTypeId, (IEnumerable<SelectListItem>)ViewBag.TemplateTypes, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TemplateTypeId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>