SmsDelivery/Controllers/FinancialsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SmsDelivery.Model;
using SmsDelivery.Model.Enums;
using SmsDelivery.Model.Interfaces;
using SmsDelivery.Models;
using SmsDelivery.ViewModels;

namespace SmsDelivery.Controllers
{
    [Authorize]
    public class FinancialsController : Controller
    {
        public string UserId => User.Identity.GetUserId();
        public IPaymentsRepository PaymentsRepository { get; set; }
        public IPaymentInstrumentsRepository PaymentInstrumentsRepository { get; set; }
        public IPaypalPaymentInstrumentRepository PaypalPaymentInstrumentRepository { get; set; }

        public FinancialsController(IPaymentInstrumentsRepository paymentInstrumentsRepository,
            IPaymentsRepository paymentsRepository, IPaypalPaymentInstrumentRepository paypalPaymentInstrumentRepository)
        {
            PaymentInstrumentsRepository = paymentInstrumentsRepository;
            PaymentsRepository = paymentsRepository;
            PaypalPaymentInstrumentRepository = paypalPaymentInstrumentRepository;
        }
        // GET: Financials
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewPayment()
        {
            return PartialView("_NewPaymentPartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreatePayment(Payment payment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userPaymentMethods = PaymentInstrumentsRepository.GetAll().Where(x => x.CustomerId.Equals(UserId));
                    PaymentInstrument paymentInstrument;

                    

                    if (userPaymentMethods.Any(x => x.IsMain))
                    {
                        paymentInstrument = userPaymentMethods.FirstOrDefault(x => x.IsMain);
                        payment.PaymentInstrumentId = paymentInstrument.Id;
                    }
                    else
                    {
                        return Json(new Response() { Success = false, Message = "No payment method" });
                    }

                    payment.Guid = new Guid();
                    payment.CreatedDate = DateTime.Now;
                    payment.CustomerId = UserId;
                    payment.Status = (int) PaymentStatus.New;
                    PaymentsRepository.Insert(payment);
                    PaymentsRepository.Save();

                    var paymentViewModel = new PaymentViewModel()
                    {
                        Amount = payment.Amount,
                        Details = payment.Description,
                        PaymentDateStr = payment.CreatedDate.ToString("g"),
                        PaymentMethod = paymentInstrument.PaypalPaymentInstrument.Account,
                        Status = PaymentStatus.New.ToString()
                    };

                    return Json(new Response { Success = true, Body = paymentViewModel});
                }
                return Json(new Response() { Success = false });
            }
            catch (Exception e)
            {
                return Json(new Response() { Success = false, Message = e.Message});
            }
            
            

        }

        public ActionResult PaymentsHistory()
        {
            var paymentMethods = PaymentInstrumentsRepository.GetAll().Where(x => x.CustomerId.Equals(UserId)).Select(s => new PaymentInstrumentViewModel()
            {
                Account = s.PaypalPaymentInstrument.Account,
                Id = s.Id,
                IsMain = s.IsMain
            }).ToList();

            var payments = PaymentsRepository.GetAll().Where(x => x.CustomerId.Equals(UserId));
            var paymentViewModelList = new List<PaymentViewModel>();
            foreach (var payment in payments)
            {
                var paymentMethod = paymentMethods.FirstOrDefault(x => x.Id == payment.PaymentInstrumentId)?.Account;
                var paymentViewModel = new PaymentViewModel()
                {
                    Amount = payment.Amount,
                    Details = payment.Description,
                    PaymentDate = payment.CreatedDate,
                    PaymentMethod = paymentMethod,
                    Status = PaymentStatus.New.ToString()
                };
                paymentViewModelList.Add(paymentViewModel);
            }

            return PartialView("_PaymentsHistory", paymentViewModelList);
        }

        public ActionResult PaymentMethods()
        {
            var pMethods = PaymentInstrumentsRepository.GetAll().Where(x => x.CustomerId.Equals(UserId)).Select(s => new PaymentInstrumentViewModel()
            {
                Account = s.PaypalPaymentInstrument.Account,
                Id = s.Id,
                IsMain = s.IsMain
            }).ToList();
            return PartialView("_PaymentMethodsPartial", pMethods);

        }

        [HttpPost]
        public JsonResult MakeMainPaymentMethod(int id)
        {
            try
            {
                var paymentMethod = PaymentInstrumentsRepository.GetById(id);
                var pMethods = PaymentInstrumentsRepository.GetAll()
                    .FirstOrDefault(x => x.CustomerId.Equals(UserId) && x.IsMain);
                if (!paymentMethod.IsMain)
                {
                    paymentMethod.IsMain = true;
                    pMethods.IsMain = false;
                    PaymentInstrumentsRepository.Save();
                    return Json(new Response() { Success = true });
                }
                return Json(new Response() { Success = false, Message = "Method already main!" });
            }
            catch
            {
                return Json(new Response() { Success = false, Message = "Error" });
            }
        }

        [HttpPost]
        public JsonResult DeletePaymentMethod(int id)
        {
            try
            {
                PaypalPaymentInstrumentRepository.Delete(id);
                PaymentInstrumentsRepository.Delete(id);
                PaypalPaymentInstrumentRepository.Save();
                PaymentInstrumentsRepository.Save();
                return Json(new Response() { Success = true });
            }
            catch
            {
                return Json(new Response() { Success = false });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreatePaymentMethod(PaymentInstrumentViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (PaymentInstrumentsRepository.GetAll().Any(x => x.CustomerId.Equals(UserId) && x.IsMain))
                {
                    model.IsMain = false;
                }
                var paymentInstrument = new PaymentInstrument()
                {
                    IsMain = model.IsMain,
                    CustomerId = UserId
                };

                PaymentInstrumentsRepository.Insert(paymentInstrument);
                PaymentInstrumentsRepository.Save();
                var paypalPaymentInstrument = new PaypalPaymentInstrument()
                {
                    Id = paymentInstrument.Id,
                    Account = model.Account
                };
                PaypalPaymentInstrumentRepository.Insert(paypalPaymentInstrument);
                PaypalPaymentInstrumentRepository.Save();

                model.Id = paypalPaymentInstrument.Id;

                return Json(new Response() {Body = model, Success = true});
            }

            return Json(new Response() {Success = false});

        }
    }
}

SmsDelivery/Views/Financials/Index.cshtml
<div class="col-md-12 pt-15px pb-10px">
    @Html.Action("NewPayment")
</div>
<div class="col-md-12 pt-15px pb-10px">
    @Html.Action("PaymentsHistory")
</div>
<div class="col-md-12 pt-15px pb-10px">
    @Html.Action("PaymentMethods")
</div>
@section modal
{
    @Html.Partial("_PaymentMethodCreateModal")
}
@section scripts{
    @Scripts.Render("~/Scripts/payment.js")
}

SmsDelivery/Views/Financials/_NewPaymentPartial.cshtml
@model SmsDelivery.Model.Payment


<div class="card card-plain">
    <div class="header">
        <h4 class="title">Make payment</h4>
        <hr />
    </div>
    <div class="content">
        @using (Html.BeginForm("CreatePayment", "Financials", FormMethod.Post, new { id = "paymentCreateForm", data_url = Url.Action("CreatePayment") }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
            <div class="col-md-6">
                <table>
                    <tbody>
                    <tr>
                        <td class="col-md-6">Enter amount</td>
                        <td class="pt-10px pb-10px">
                            @Html.EditorFor(model => model.Amount, new {htmlAttributes = new {@class = "form-control", placeholder = "Enter amount"}})
                            @Html.ValidationMessageFor(model => model.Amount, "", new {@class = "text-danger"})
                        </td>
                    </tr>
                    @*<tr>
                            <td rowspan="3">Payment options</td>
                            <td class="pt-10px pb-10px">@Html.RadioButton("Credit Card", true)<span>Credit Card</span></td>
                        </tr>*@
                    @*<tr>
                        <td class="pt-10px pb-10px">@Html.RadioButton("Paypal", false)<span>Paypal</span></td>
                    </tr>
                    <tr>
                        <td class="pt-10px pb-10px">@Html.RadioButton("Bank transfer", false)<span>Bank transfer</span></td>
                    </tr>*@

                    </tbody>
                </table>
            </div>
            <div class="col-md-6">

                @*<table>
                    <tbody>
                    <tr>
                        <td colspan="2" class="pt-10px pb-10px">Summary</td>
                    </tr>
                    <tr class="col-md-10">
                        <td class="pull-left pt-10px pb-10px">Total(excl VAT)</td>
                        <td class="pull-right pt-10px pb-10px"><b>$ 300</b></td>
                    </tr>
                    <tr class="col-md-10 bt-1px">
                        <td class="pull-left pt-10px pb-10px">Total VAT(21%)</td>
                        <td class="pull-right pt-10px pb-10px"><b>$ 300</b></td>
                    </tr>
                    <tr class="col-md-10 bt-1px">
                        <td class="pull-left pt-10px pb-10px">Total(incl VAT)</td>
                        <td class="pull-right pt-10px pb-10px"><b>$ 300</b></td>
                    </tr>
                    </tbody>
                </table>*@
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-info btn-fill btn-wd">Save Changes</button>
        </div>
        }
        
    </div>
</div>

SmsDelivery/Views/Financials/_PaymentMethodCreateModal.cshtml
@model SmsDelivery.ViewModels.PaymentInstrumentViewModel
<div class="modal fade" id="paymentMethodCreateModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" style="background-color: #d3d3d3;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New Payment Method</h4>
            </div>
            <div class="modal-body" style="background-color: #d3d3d3;">
                @using (Html.BeginForm("CreatePaymentMethod", "Financials", FormMethod.Post, new { id = "paymentMethodCreateModalForm", data_url = Url.Action("CreatePaymentMethod") }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="alert alert-danger hide" id="validationErrors">
                            <ul></ul>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsMain, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.CheckBoxFor(model => model.IsMain, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.IsMain, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>

SmsDelivery/Views/Financials/_PaymentMethodsPartial.cshtml
@model IEnumerable<SmsDelivery.ViewModels.PaymentInstrumentViewModel>
<div class="card card-plain">
    <div class="header">
        <h4 class="title">Make payment</h4>
        <hr />
    </div>
    <div class="content payment-methods-container">
        <div class="row">
            @if (Model.Any())
            {
                foreach (var item in Model)
                {
                    @Html.DisplayFor(model => item)
                }
            }
            else
            {
                <div class="text-center" id="paymentMethodsNoData"><p>No data</p></div>
            }
        </div>
        <input type="hidden" id="paymentMethodDeleteUrl" data-url="@Url.Action("DeletePaymentMethod")"/>
        <input type="hidden" id="paymentMethodMakeMainUrl" data-url="@Url.Action("MakeMainPaymentMethod")"/>
        <div class="text-center">
            <button type="submit" data-toggle="modal" data-target="#paymentMethodCreateModal" class="btn btn-info btn-fill btn-wd">New Payment method</button>
        </div>
    </div>
</div>

SmsDelivery/Views/Financials/_PaymentsHistory.cshtml
@using SmsDelivery.Model
@using SmsDelivery.ViewModels
@model IEnumerable<PaymentViewModel>

<div class="card card-plain">
    <div class="header">
        <h4 class="title">Payments history</h4>
        <hr />
    </div>
    <div class="content table-responsive table-full-width payments-history-container">
        <table class="table table-hover">
            <thead>
            <th>Payment Date</th>
            <th>Amount</th>
            <th>Payment Method</th>
            <th>Details</th>
            <th>Status</th>
            </thead>
            <tbody>
            @if (Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.PaymentDate.ToString("g")</td>
                        <td>@item.Amount</td>
                        <td>@item.PaymentMethod</td>
                        <td>@item.Details</td>
                        <td>@item.Status</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5" class="text-center" id="noPaymentsDataRow">No data</td>
                </tr>
            }

            </tbody>
        </table>
    </div>
</div>